#!/bin/bash
# ============================================================
#  CentralLog — One-shot setup for Kali (all-in-one machine)
#  Run as root:  sudo bash setup_kali.sh
# ============================================================
set -e

# ── Colours ─────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[*]${NC} $1"; }
ok()    { echo -e "${GREEN}[+]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
fail()  { echo -e "${RED}[-]${NC} $1"; exit 1; }

# ── Must be root ────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    fail "Run this script as root:  sudo bash $0"
fi

# ── Configurable variables ──────────────────────────────────
PROJECT_SRC="$(cd "$(dirname "$0")/.." && pwd)"   # auto-detect project root
WEB_ROOT="/var/www/centrallog"
DB_NAME="centrallog"
DB_USER="centrallog_user"
DB_PASS="$(openssl rand -base64 18)"              # random DB password
INGEST_TOKEN="$(openssl rand -hex 24)"            # random ingest token
SSH_KEY_PATH="/root/.ssh/centrallog"

echo ""
echo "========================================"
echo "   CentralLog — Kali Setup Script"
echo "========================================"
echo ""
info "Project source : $PROJECT_SRC"
info "Web root       : $WEB_ROOT"
echo ""

# ── 1. Install packages ────────────────────────────────────
info "Installing Apache, MariaDB, PHP, and tools..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq

apt-get install -y -qq \
    apache2 \
    mariadb-server \
    php php-mysql php-curl php-mbstring php-xml php-zip php-gd php-json \
    libapache2-mod-php \
    curl jq git unzip \
    openssh-server \
    2>/dev/null

ok "Packages installed."

# ── 2. Install Composer (if missing) ───────────────────────
if ! command -v composer &>/dev/null; then
    info "Installing Composer..."
    EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
    if [[ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]]; then
        rm composer-setup.php
        fail "Composer installer checksum mismatch — aborting."
    fi
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
    rm composer-setup.php
    ok "Composer installed."
else
    ok "Composer already installed."
fi

# ── 3. Start services ──────────────────────────────────────
info "Starting Apache & MariaDB..."
systemctl enable --now apache2 2>/dev/null || true
systemctl enable --now mariadb  2>/dev/null || true
systemctl enable --now ssh      2>/dev/null || true
ok "Services started."

# ── 4. Database setup ──────────────────────────────────────
info "Setting up database..."
# Import schema (creates DB + tables + seed data)
mysql < "$PROJECT_SRC/sql/schema.sql" 2>/dev/null || true

# Create app DB user
mysql <<EOSQL
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOSQL

# Reset admin password to 'admin' with a fresh bcrypt hash
ADMIN_HASH=$(php -r "echo password_hash('admin', PASSWORD_BCRYPT);")
mysql "$DB_NAME" -e "UPDATE users SET password_hash='${ADMIN_HASH}' WHERE username='admin';"
ok "Database '$DB_NAME' ready — user: $DB_USER"
ok "Admin password reset to 'admin'"

# ── 5. Deploy project to web root ──────────────────────────
info "Deploying project to $WEB_ROOT ..."
rm -rf "$WEB_ROOT"
cp -a "$PROJECT_SRC" "$WEB_ROOT"
chown -R www-data:www-data "$WEB_ROOT"
ok "Project deployed."

# ── 6. Install PHP dependencies ────────────────────────────
info "Installing PHP dependencies (phpseclib) ..."
cd "$WEB_ROOT"
COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --quiet 2>/dev/null || \
COMPOSER_ALLOW_SUPERUSER=1 composer require phpseclib/phpseclib:~3.0 --no-interaction --quiet
chown -R www-data:www-data "$WEB_ROOT/vendor"
ok "Composer dependencies installed."

# ── 7. Generate SSH key for localhost ───────────────────────
if [[ ! -f "$SSH_KEY_PATH" ]]; then
    info "Generating SSH key for local log pull..."
    ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -q
    # Authorise the key on this same machine
    mkdir -p /root/.ssh && chmod 700 /root/.ssh
    cat "${SSH_KEY_PATH}.pub" >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    ok "SSH key created & authorized."
else
    ok "SSH key already exists at $SSH_KEY_PATH"
fi

# ── 8. Write config.php ────────────────────────────────────
info "Writing config.php ..."
cat > "$WEB_ROOT/config.php" <<EOPHP
<?php
/**
 * CentralLog — Configuration (auto-generated by setup_kali.sh)
 */

// Database
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');

// SSH to target (localhost — same machine)
define('SSH_HOST', '127.0.0.1');
define('SSH_PORT', 22);
define('SSH_USER', 'root');
define('SSH_KEY',  '${SSH_KEY_PATH}');

// Ingest API shared secret
define('INGEST_TOKEN', '${INGEST_TOKEN}');

// Session
define('SESSION_NAME', 'centrallog_sess');
define('SESSION_LIFETIME', 3600);

// Timezone
date_default_timezone_set('UTC');
EOPHP
chown www-data:www-data "$WEB_ROOT/config.php"
chmod 640 "$WEB_ROOT/config.php"
ok "config.php written."

# ── 9. Configure push_logs.sh for localhost ─────────────────
info "Configuring push_logs.sh for local log push..."
PUSH_SCRIPT="$WEB_ROOT/scripts/push_logs.sh"
sed -i "s|^DASHBOARD_URL=.*|DASHBOARD_URL=\"http://127.0.0.1/api/ingest.php\"|" "$PUSH_SCRIPT"
sed -i "s|^TOKEN=.*|TOKEN=\"${INGEST_TOKEN}\"|" "$PUSH_SCRIPT"
chmod +x "$PUSH_SCRIPT"
ok "push_logs.sh configured."

# ── 10. Apache virtual host ────────────────────────────────
info "Configuring Apache..."
cat > /etc/apache2/sites-available/centrallog.conf <<EOVHOST
<VirtualHost *:80>
    ServerName centrallog.local
    DocumentRoot ${WEB_ROOT}

    <Directory ${WEB_ROOT}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog  \${APACHE_LOG_DIR}/centrallog_error.log
    CustomLog \${APACHE_LOG_DIR}/centrallog_access.log combined
</VirtualHost>
EOVHOST

a2enmod rewrite          2>/dev/null || true
a2dissite 000-default    2>/dev/null || true
a2ensite centrallog      2>/dev/null || true
systemctl reload apache2
ok "Apache configured & reloaded."

# ── 11. Cron job for log pushing ────────────────────────────
info "Setting up cron for log ingestion..."
CRON_LINE="* * * * * ${WEB_ROOT}/scripts/push_logs.sh >/dev/null 2>&1"
( crontab -l 2>/dev/null | grep -v "push_logs.sh"; echo "$CRON_LINE" ) | crontab -
ok "Cron job installed (pushes logs every minute)."

# ── 12. Quick sanity check ─────────────────────────────────
info "Running sanity checks..."

# Check Apache serves something
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/ 2>/dev/null || echo "000")
if [[ "$HTTP_CODE" == "200" || "$HTTP_CODE" == "302" ]]; then
    ok "Apache is serving CentralLog (HTTP $HTTP_CODE)"
else
    warn "Apache returned HTTP $HTTP_CODE — may need a manual check."
fi

# Check DB connectivity
if php -r "
    require '${WEB_ROOT}/config.php';
    try { new PDO('mysql:host='.DB_HOST.';port='.DB_PORT.';dbname='.DB_NAME, DB_USER, DB_PASS);
          echo 'ok'; } catch(Exception \$e) { echo 'fail'; }
" 2>/dev/null | grep -q ok; then
    ok "PHP → MySQL connection works."
else
    warn "PHP → MySQL connection failed — check credentials."
fi

# ── Done ────────────────────────────────────────────────────
echo ""
echo "========================================"
echo -e "${GREEN}   CentralLog is ready!${NC}"
echo "========================================"
echo ""
echo "  Dashboard  : http://127.0.0.1/"
echo "  Login      : admin / admin  (change on first login)"
echo ""
echo "  DB user    : $DB_USER"
echo "  DB pass    : $DB_PASS"
echo "  Ingest key : $INGEST_TOKEN"
echo ""
echo "  Logs are pushed to the dashboard every minute via cron."
echo "  Generate attack traffic (nmap, hydra, nikto) against"
echo "  127.0.0.1 and watch the dashboard light up."
echo ""
echo "  Save these credentials somewhere safe!"
echo "========================================"
echo ""
